ScoopInstaller/Java

adopt8-hotspot.json

Fixes adopt8 too as mentioned in #9

Fix extract dir for AdoptOpenJDK 8 Hotspot

---

oraclejdk-lts.json
oraclejdk.json
oraclejdk11.json

Oracle JDK 11: Update license and change to https for homepage

---

appveyor.yml

Fix PowerShell 6 build failure.

fix(appveyor): Use VS2019 image

---

bucket/openjdk.json

openjdk: Update to version 13-33

---

bucket/openjdk12.json

JDK 12 releases program has concluded.

openjdk12: Remove checkver

---

bucket/adopt10-openj9.json
bucket/adopt11-openj9-jre.json
bucket/adopt11-openj9.json
bucket/adopt12-openj9-jre.json
bucket/adopt12-openj9.json
bucket/adopt13-openj9-jre.json
bucket/adopt13-openj9.json
bucket/adopt9-openj9.json
bucket/adoptopenjdk-lts-openj9-jre.json
bucket/adoptopenjdk-lts-openj9.json
bucket/adoptopenjdk-openj9-jre.json
bucket/adoptopenjdk-openj9.json

AdoptOpenJDK: Fix extract_dir

---

bucket/zulu.json
bucket/zulu10.json
bucket/zulu11-jre.json
bucket/zulu11.json
bucket/zulu12.json
bucket/zulu13.json
bucket/zulu6.json
bucket/zulu7.json
bucket/zulu8-jre.json
bucket/zulu9.json
bucket/zulufx.json
bucket/zulufx11-jre.json
bucket/zulufx11.json
bucket/zulufx8-jre.json
bucket/zulufx8.json

My solution combine the:
https://cdn.azul.com/zulu/bin/?C=M;O=D and https://www.azul.com/wp-admin/admin-ajax.php?action=search_bundles

Fixed zulu checkver (close #69)

---

bucket/oraclejre8.json

Oracle JRE 8: Manually set BundleId

---

bucket/liberica-full-jre.json
bucket/liberica-full-lts-jre.json
bucket/liberica-full-lts.json
bucket/liberica-full.json
bucket/liberica-jre.json
bucket/liberica-lite-lts.json
bucket/liberica-lite.json
bucket/liberica-lts-jre.json
bucket/liberica-lts.json
bucket/liberica.json
bucket/liberica11-full-jre.json
bucket/liberica11-full.json
bucket/liberica11-jre.json
bucket/liberica11-lite.json
bucket/liberica11.json
bucket/liberica12-lite.json
bucket/liberica13-full-jre.json
bucket/liberica13-full.json
bucket/liberica13-jre.json
bucket/liberica13-lite.json
bucket/liberica13.json
bucket/liberica8-full-jre.json
bucket/liberica8-full.json

Fixes #123 
Closes #126, closes #127, closes #128, closes #129, closes #130

Liberica: Switch to BellSoft API

---

bucket/zulu-jre.json
bucket/zulu.json
bucket/zulu10.json
bucket/zulu11-jre.json
bucket/zulu11.json
bucket/zulu12.json
bucket/zulu13-jre.json
bucket/zulu13.json
bucket/zulu6.json
bucket/zulu7.json
bucket/zulu8-jre.json
bucket/zulu8.json
bucket/zulu9.json
bucket/zulufx-jre.json
bucket/zulufx.json
bucket/zulufx11-jre.json
bucket/zulufx8-jre.json
bucket/zulufx8.json

Zulu: Use official API for autoupdate

---

bucket/dragonwell8.json

As suggested in #117 
Dragonwell 11 is not yet available for Windows.

Add Dragonwell 8 JDK

---

bucket/gluon-openjfx-jmods-ea.json
bucket/gluon-openjfx-jmods-lts.json
bucket/gluon-openjfx-jmods.json
bucket/gluon-openjfx-sdk-ea.json
bucket/gluon-openjfx-sdk-lts.json
bucket/gluon-openjfx-sdk.json

Add OpenJFX by Gluon

---

bucket/liberica14-full-jre.json
bucket/liberica14-full.json
bucket/liberica14-jre.json
bucket/liberica14-lite.json
bucket/liberica14.json

Please add the latest Liberica JDK release.

Add Liberica JDK 14 release.

---

bucket/oraclejre8.json

oraclejre8: Update download URL, Hash fix

---

bucket/adopt11-hotspot-jre.json
bucket/adopt11-hotspot.json
bucket/adopt14-hotspot-jre.json
bucket/adopt14-hotspot.json
bucket/adopt8-hotspot-jre.json
bucket/adopt8-hotspot.json
bucket/adoptopenjdk-hotspot-jre.json
bucket/adoptopenjdk-hotspot.json
bucket/adoptopenjdk-lts-hotspot-jre.json
bucket/adoptopenjdk-lts-hotspot.json

Add patch version to hotspot manifests

---

bucket/adopt8-hotspot-jre.json
bucket/adopt8-hotspot.json

adopt8-hotspot: Fix extract_dir

---

bucket/adopt8-hotspot-jre.json

the extract dir in the manifest generates the error:
Could not find 'jdk8u252-b09'! (error 16)
edit: also here #175

fix extract dir

---

bucket/liberica11-full-jre.json
bucket/liberica11-full.json

liberica11-full(-jre): Add -full to extract_dir

---

bucket/liberica-full-lts-jre.json
bucket/liberica-full-lts.json
bucket/liberica8-full-jre.json
bucket/liberica8-full.json

Liberica: Fix missing -full suffix in extract_dir

---

bucket/adopt15-hotspot-jre-nightly.json
bucket/adopt15-hotspot-jre.json
bucket/adopt15-hotspot-nightly.json
bucket/adopt15-hotspot.json
bucket/adopt15-openj9-jre-nightly.json
bucket/adopt15-openj9-jre.json
bucket/adopt15-openj9-nightly.json
bucket/adopt15-openj9-xl-jre-nightly.json
bucket/adopt15-openj9-xl-jre.json
bucket/adopt15-openj9-xl-nightly.json
bucket/adopt15-openj9-xl.json
bucket/adopt15-openj9.json

add separate adopt15 definitions with nightlies

---

bucket/adopt16-hotspot-nightly.json
bucket/adopt16-openj9-jre-nightly.json
bucket/adopt16-openj9-nightly.json
bucket/adopt16-openj9-xl-jre-nightly.json
bucket/adopt16-openj9-xl-nightly.json

No hotspot-jre available through API.

Add AdoptOpenJDK 16

---

bucket/liberica-jre.json
bucket/liberica-lite.json
bucket/liberica.json
bucket/liberica15-full-jre.json
bucket/liberica15-full.json
bucket/liberica15-jre.json
bucket/liberica15-lite.json
bucket/liberica15.json
bucket/liberica8-full-jre.json
bucket/liberica8-full.json
bucket/liberica8-jre.json
bucket/liberica8.json

liberica*: Fix hashes

---

bucket/visualvm.json

Add visual VM

---

bucket/graalvm-annual-jdk11.json
bucket/graalvm-annual-jdk8.json
bucket/graalvm-annual.json
bucket/graalvm-jdk11.json
bucket/graalvm-jdk8.json
bucket/graalvm-lts-jdk11.json
bucket/graalvm-lts-jdk8.json
bucket/graalvm-lts.json
bucket/graalvm-nightly-jdk11.json
bucket/graalvm-nightly-jdk16.json
bucket/graalvm-nightly.json
bucket/graalvm.json

graalvm*: Manifest maintenance

---

bucket/microsoft-jdk.json

Add microsoft-jdk, closes #266

Add microsoft-jdk version 11.0.10.9

---

bucket/zulu16-jdk.json
bucket/zulufx16-jdk.json

zulufx16-jdk: Fix hash

---

bucket/graalvm-annual-jdk11.json
bucket/graalvm-annual-jdk8.json
bucket/graalvm-annual.json
bucket/graalvm-jdk11.json
bucket/graalvm-jdk8.json
bucket/graalvm-lts.json
bucket/graalvm.json

Resolves #279, resolved #280, resolved #281.

graalvm*: Update hashes

---

bucket/corretto.json
bucket/corretto11.json
bucket/corretto8-jre.json
bucket/corretto8.json

corretto*: Change to extract_dir.

---

bucket/temurin8-jre.json

temurin8-jre: Fix extract_dir

---

bucket/temurin11-jre.json

fix(temurin11-jre): wrong extract_dir path

---

bucket/microsoft-jdk.json
bucket/microsoft-lts-jdk.json
bucket/microsoft17-jdk.json

Fix microsoft-jdk 17.0.3

---

bucket/openjdk19.json

openjdk19: Add version 19-25-ea

---

bucket/oraclejre8.json

oraclejre8: fix wrong url for 8u341(#416)

---

bucket/microsoft-lts-jdk.json
bucket/microsoft11-jdk.json
bucket/microsoft16-jdk.json
bucket/microsoft17-jdk.json

Relates to #390 and https://github.com/ScoopInstaller/Java/commit/901d714b818da4243411c6142427be5239f0e817#commitcomment-82031895
Closes #421
Uses installer script from temurin-nightly-jdk

microsoft*-jdk: Fix extract_dir issues

---

bucket/temurin18-jdk.json
bucket/temurin18-jre.json
bucket/temurin19-jdk.json
bucket/temurin19-jre.json

This PR adds
- Temurin 18 JRE
- Temurin 18 JDK
- Temurin 19 JRE
- Temurin 19 JDK

temurin: add versions 18 and 19

---

bucket/oraclejre8.json

Fixes the download url calculation.
Closes #439

oraclejre8: Fix 64bit url

---

bucket/libericamc.json
bucket/libericamc7.json
bucket/libericamc8.json

Added libericamc7 and libericamc8. Updated `chechver` in libericamc.
Closes #442

libericamc: Manifest maintenance

---

bucket/intellij-jbr17-jcef.json
bucket/intellij-jbr17-sdk-jcef.json
bucket/intellij-jbr17-sdk.json
bucket/intellij-jbr17.json

intellij-jbr17*: Fix extract_dir issues

---

bucket/microsoft-jdk.json
bucket/microsoft-lts-jdk.json
bucket/microsoft11-jdk.json
bucket/microsoft16-jdk.json
bucket/microsoft17-jdk.json

microsoft-jdk: Add arm64 architecture

---

bucket/openjdk.json

openjdk: Update to version 20.0.1-9

---

bucket/dragonwell8-jdk-standard.json
bucket/dragonwell8-jdk.json

See https://github.com/dragonwell-project/dragonwell8/wiki/Alibaba-Dragonwell8-Standard-Edition-Release-Notes#alibaba-dragonwell-81617-ga
Please note that drangonwell8 has been divided into two versions: **standard** and **extended**.
Closes #XXXX
Relates to #XXXX

dragonwell8-jdk: Update version to 8.16.17-8.0.382

---

bucket/dragonwell17-jdk-standard.json
bucket/dragonwell17-jdk.json

See https://github.com/dragonwell-project/dragonwell17/wiki/Alibaba-Dragonwell-17-Standard-Edition-Release-Notes#1708087
The regex seems to be outdated, I made some small changes and don't know if it will work as expected
Currently dragonwell17 only has **standard** edtion, but it is foreseeable that there will be an **extended** edition in the future
Closes #XXXX
Relates to #XXXX

dragonwell17-jdk: Update version to 17.0.8.0.8-17.0.8

---

bucket/openjdk-ea.json
bucket/openjdk.json
bucket/openjdk22.json

Relates to https://github.com/ScoopInstaller/Java/pull/487

Update OpenJDK: General-Availability to 21 and Early-Access to 22

---

bucket/oraclejdk.json

Relates to https://github.com/ScoopInstaller/Java/pull/486

Update Oracle JDK to JDK 21

---

bucket/oraclejdk-lts.json

Update oraclejdk-lts.json to Java 21

---

bucket/corretto-jdk.json

Updated Corretto JDK to latest Version 20.

corretto-jdk: Update to version 20.0.2.10.1

---

bucket/temurin17-jdk.json
bucket/temurin17-jre.json

temurin17: Fix extract_dir

---

bucket/dragonwell11-jdk-extended.json
bucket/dragonwell8-jdk-extended.json

See 
- [Dragonwell8 Extended Edition Release Notes](https://github.com/dragonwell-project/dragonwell8/wiki/Alibaba-Dragonwell8-Extended-Edition-Release-Notes)
- [Dragonwell11 Extended Edition Release Notes](https://github.com/dragonwell-project/dragonwell11/wiki/Alibaba-Dragonwell-11-Extended-Edition-Release-Notes)
Closes #482

dragonwell-jdk-extended: Add version 8.16.17-8.0.382 and 11.0.20.16-11.0.20

---

bucket/intellij-jbr11-jcef.json
bucket/intellij-jbr11-sdk-jcef.json
bucket/intellij-jbr11-sdk.json
bucket/intellij-jbr11.json
bucket/intellij-jbr17-jcef.json
bucket/intellij-jbr17-sdk-jcef.json
bucket/intellij-jbr17-sdk.json
bucket/intellij-jbr17.json

intellij-jbr*: Update checkver

---

bucket/temurin21-jdk.json
bucket/temurin21-jre.json

This adds two new apps for temurin-21
I accidentally closed the previous PR and was not able to reopen it, sorry

temurin: Add version 21

---

bucket/temurin20-jdk.json
bucket/temurin20-jre.json

Add missing version 20 for temurin

temurin: Add version 20

---

bucket/temurin22-jdk.json
bucket/temurin22-jre.json

This adds two new apps for temurin-22

temurin: Add version 22

---

bucket/intellij-jbr21-jcef.json
bucket/intellij-jbr21-sdk-jcef.json
bucket/intellij-jbr21-sdk.json
bucket/intellij-jbr21.json

intellij-jbr: Add support for JetBrains Runtime 21 (#524)

---

bucket/dragonwell21-jdk.json

See [Dragonwell-21-Standard-Edition-Release-Notes](https://github.com/dragonwell-project/dragonwell21/wiki/Alibaba-Dragonwell-21-Standard-Edition-Release-Notes)
Relates to [#522 ](https://github.com/ScoopInstaller/Java/issues/522)

Add dragonwell21-jdk

---

bucket/temurin23-jdk.json
bucket/temurin23-jre.json

This adds two new apps for temurin-23

temurin: Add version 23

---

bucket/oraclejre8.json

oraclejre8: Deprecate manifest

---

bucket/temurin24-jdk.json
bucket/temurin24-jre.json

This adds two new apps for temurin-24

temurin: Add version 24

---

bucket/oraclejdk-lts.json
bucket/oraclejdk.json

update oraclejdk to 24.0.2, oraclejdk-lts to 21.0.8
