ScoopInstaller/Java

bucket/graalvm.json

GraalVM is a polyglot JVM/JIT supporting Java/Scala/Kotlin, JavaScript/NodeJS, Ruby, Python, R + any-LLVM based languages, with fast & compact AOT/native image executables
https://www.graalvm.org
GraalVM 19.0 Released - First production release of the revolutionary polyglot virtual machine / @GraalVM
https://medium.com/graalvm/announcing-graalvm-19-4590cf354df8
https://www.graalvm.org/docs/release-notes/#1900
https://www.graalvm.org/downloads/
https://www.graalvm.org/docs/reference-manual/graal-updater/
https://www.graalvm.org/docs/reference-manual/aot-compilation/

Add GraalVM CE v19.0.0 - Polyglot Virtual Machine for JVM, JavaScript, LLVM..

---

bucket/openjdk-ea.json

JDK 14 is Early-Access Build now and should be named as `openjdk-ea`.

openjdk14: Rename to openjdk-ea

---

bucket/adopt13-hotspot-jre.json
bucket/adopt13-hotspot.json
bucket/adopt13-openj9-jre.json
bucket/adopt13-openj9.json

This PR adds the following releases:  
`adopt13-hotspot`  
`adopt13-hotspot-jre`  
`adopt13-openj9`  
`adopt13-openj9-jre`
~Note: The HotSpot release versions point to `jdk-13+33` because a 32-bit build is not yet available for `jdk-13.0.1+9`.~
Edit: All versions now point to `13.0.1+9`.

AdoptOpenJDK 13: Add releases

---

bucket/graalvm-nightly.json
bucket/graalvm.json
bucket/graalvm11-nightly.json
bucket/graalvm11.json
bucket/graalvm8-nightly.json
bucket/graalvm8.json

Most applications expect GRAALVM_HOME to be present when GraalVM is
installed.
See the documentation from quarkus: https://quarkus.io/guides/building-native-image

Export GRAALVM_HOME on install.

---

bucket/liberica-full-jre.json
bucket/liberica-full-lts-jre.json
bucket/liberica-full-lts.json
bucket/liberica-full.json
bucket/liberica-jre.json
bucket/liberica-lite-lts.json
bucket/liberica-lite.json
bucket/liberica-lts-jre.json
bucket/liberica-lts.json
bucket/liberica.json
bucket/liberica11-full-jre.json
bucket/liberica11-full.json
bucket/liberica11-jre.json
bucket/liberica11-lite.json
bucket/liberica11.json
bucket/liberica13-lite.json
bucket/liberica13.json
bucket/liberica14-full-jre.json
bucket/liberica14-full.json
bucket/liberica14-jre.json
bucket/liberica14-lite.json
bucket/liberica14.json

1. Removed a redundant capture group for trailing zeroes. Recently API was fixed accordingly to JEP-322 (A version number never has trailing zero elements. If an element and all those that follow it logically have the value zero then all of them are omitted.).
2. Regular bundles for 13.0.2+9 were reuploaded as they contained FX libraries by mistake, so I updated their checksums.
3. Fixed extract directories for 11.0.6 and 13.0.2 lite bundles. All subsequent releases will follow the next rules: lite bundles are extracted into jdk-<VNUM>-lite directory, regulars into jdk-<VNUM> and full into jdk-<VNUM>-full.

A bunch of fixes for Liberica installers.

---

bucket/liberica8-full-jre.json
bucket/liberica8-full.json
bucket/liberica8-jre.json
bucket/liberica8.json

1) Fixed wrong checksums caused by caching issues.
2) Fixed extract_dir for full bundles.

Fixed problems with installing Liberica JDK 8

---

bucket/openjdk.json

With checkver updated, autoupdate would be able to update Scoop
> openjdk: 15.0.1-9 (scoop version is 14.0.2-12) autoupdate available

Update OpenJDK Checkver page to OpenJDK 15

---

bucket/oraclejre8.json

Disable autoupdate, whole download page is rendered in JavaScript, unable to parse it.

oraclejre8: Update to version 8u271

---

bucket/openjdk8-redhat-jre.json
bucket/openjdk8-redhat.json

openjdk8: Use the unaltered builds from Red Hat

---

bucket/oraclejre8.json

Still unable to get the actual bundleid. The correct bundleid can be calculated by adding `1` to the windows offline packages (`win_offline_bundle` and `win_x64_bundle`). The bundleid change after each new release.

oraclejre8: Add checkver

---

bucket/openjdk.json

Updating checkver will allow auto updater to detect v16 and update accordingly

openjdk: Update checkver to version 16

---

bucket/oraclejre8.json

`extract_dir` wasn't changed in last update to 8u281.

oraclejre8: Fix extract_dir name

---

bucket/zulumc.json

The current manifest has wrong entries for extract directory and hence the install is incorrect. Additionally, persistence causes the app to break at runtime.
```powershell
❯ scoop install zulumc
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'zulumc' (8.1.0.42) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: e6fabd|OK  |   3.7MiB/s|D:/scoop/cache/zulumc#8.1.0.42#https_cdn.azul.com_zmc_bin_zmc8.1.0.42-ca-win_x64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of zmc8.1.0.42-ca-win_x64.zip ... …
```

Fix broken zulumc installer 💉

---

bucket/openjdk.json

Version 18 has appeared in GA list.
And version 17 has been superseded.
Closes #382

openjdk: Update to version 18.0.1.1-2

---

bucket/oraclejre8.json

Value for win64 tar changed from one which blocked the checkver.
It should auto-update automatically (i tested on my computer), and it installed fine after.

oraclejre8@8u321: update manifest following a url change

---

bucket/ojdkbuild-jre.json
bucket/ojdkbuild.json
bucket/ojdkbuild10-full.json
bucket/ojdkbuild10.json
bucket/ojdkbuild11-full.json
bucket/ojdkbuild11-jre.json
bucket/ojdkbuild12-full.json
bucket/ojdkbuild12.json
bucket/ojdkbuild13-full.json
bucket/ojdkbuild13-jre.json
bucket/ojdkbuild14-full.json
bucket/ojdkbuild14-jre.json
bucket/ojdkbuild15-full.json
bucket/ojdkbuild15-jre.json
bucket/ojdkbuild15.json
bucket/ojdkbuild17-full.json
bucket/ojdkbuild17-jre.json
bucket/ojdkbuild17.json
bucket/ojdkbuild8-full.json
bucket/ojdkbuild8-jre.json
bucket/ojdkbuild8.json
bucket/ojdkbuild9-full.json
bucket/ojdkbuild9.json

The ojdkbuild project is discontinued, see https://github.com/ojdkbuild/ojdkbuild/commit/43f504d8e1397b09fecd5431a71fe2626503fc4c

ojdkbuild: Deprecate manifests

---

bucket/graalvm.json

Since we do have a graalvm-jdk17.json, I thought this would be more appropriate than creating a new file.

graalvm: Update GraalVM to JDK 19

---

bucket/openjdk-ea.json
bucket/openjdk20.json
bucket/openjdk21.json

Update `openjdk-ea` to version `21-2-ea`.
Added `openjdk21.json`.

openjdk-ea: Update to version 21-2-ea

---

bucket/intellij-jbr11-jcef.json
bucket/intellij-jbr11-sdk-jcef.json
bucket/intellij-jbr11-sdk.json
bucket/intellij-jbr11.json
bucket/intellij-jbr17-jcef.json
bucket/intellij-jbr17-sdk-jcef.json
bucket/intellij-jbr17-sdk.json
bucket/intellij-jbr17.json

Fixes jbr hashes. They are using sha512 now

intellij-jbr*: hashes fix. Now sha512

---

bucket/.gitkeep

Removes the .gitkeep file that should not be there, as indicated by the contents which state, "Delete this '.gitkeep' file once this directory has any files"

chore: Remove .gitkeep

---

bucket/openjdk.json

Close #493
Openjdk.json will have problems during installation
I modified the openjdk.json file

openjdk@21-35: fixed issue with unzipping folders

---

bucket/corretto20-jdk.json
bucket/corretto21-jdk.json

Noticed that Corretto 20 and 21 has no manifest, while Java 21 released recently. 
Used the corretto19-jdk.json as a template for 20 and 21 and the official resources for the version checking and hash. 
Local installation indicate the correct JDKs were installed, IntelliJ recognizes both.

Added support for Corretto 20 and 21

---

bucket/graalvm21-jdk21.json

Addition of graalvm-jdk21-21.0.1.
Addition of GraalVM 21.0.1 for JDK21.
Closes #489

graalmvm21-jdk21

---

bucket/graalvm-oracle-17jdk.json
bucket/graalvm-oracle-21jdk.json
bucket/graalvm-oracle-jdk.json

Relates to #472
JDK 20 is not in current releases now. I included 21 instead.
Since graalvm21-jdk21 got created recently, I didn't add/modify the ce one according to https://github.com/ScoopInstaller/Java/issues/472#issuecomment-1702439789 .

graalvm-oracle-jdk: Add version 21.0.2 / 17.0.10

---

bucket/corretto22-jdk.json
bucket/corretto23-jdk.json

This PR adds support for installing and updating Amazon Corretto 22 and 23.
The install and update script is based on the Corretto 21 script

added support for corretto 22 and 23

---

bucket/liberica-full-jdk.json
bucket/liberica-full-jre.json
bucket/liberica-full-lts-jdk.json
bucket/liberica-full-lts-jre.json
bucket/liberica-jdk.json
bucket/liberica-jre.json
bucket/liberica-lite-jdk.json
bucket/liberica-lite-lts-jdk.json
bucket/liberica-lts-jdk.json
bucket/liberica-lts-jre.json
bucket/liberica21-full-jdk.json
bucket/liberica21-full-jre.json
bucket/liberica21-full-lts-jdk.json
bucket/liberica21-full-lts-jre.json
bucket/liberica21-jdk.json
bucket/liberica21-jre.json
bucket/liberica21-lite-jdk.json
bucket/liberica21-lite-lts-jdk.json
bucket/liberica21-lts-jdk.json
bucket/liberica21-lts-jre.json
bucket/liberica25-full-jdk.json
bucket/liberica25-full-jre.json
bucket/liberica25-full-lts-jdk.json
bucket/liberica25-full-lts-jre.json
bucket/liberica25-jdk.json
bucket/liberica25-jre.json
bucket/liberica25-lite-jdk.json
bucket/liberica25-lite-lts-jdk.json
bucket/liberica25-lts-jdk.json
bucket/liberica25-lts-jre.json

Closes #556 
This PR also includes many new Liberica packages for Java 21 and Java 25.

fix(liberica): Update to Java 25 and Replace 32-bit to ARM64
